-- ===========================================================================
-- Seed: all proposed interview questions (shared bank + role-specific banks).
-- 120 questions total. Positions are sequential; the interview page
-- orders by position. Safe to re-run after truncating public.questions.
-- ===========================================================================

insert into public.questions (position, prompt) values
  -- Introduction (shared)
  (1, 'Could you confirm your full name and briefly introduce yourself?'),
  (2, 'Walk me through your career so far in about two minutes.'),
  (3, 'What drew you to apply for this role at X Spark?'),
  (4, 'What are you hoping to learn or grow into over the next couple of years?'),
  (5, 'Before we dive in, is there anything about your background you''d like to highlight that isn''t obvious from your CV?'),
  -- Background (shared)
  (6, 'Tell me about the project you''re proudest of and why.'),
  (7, 'How did you get started in software development?'),
  (8, 'Describe a time you had to learn a new technology quickly for a project.'),
  (9, 'What''s the most complex system you''ve worked on, and what was your role in it?'),
  (10, 'How do you usually onboard onto an unfamiliar codebase?'),
  (11, 'Tell me about a project that didn''t go as planned. What happened?'),
  (12, 'What kind of projects energise you the most, and why?'),
  (13, 'How has your approach to development changed over your career so far?'),
  (14, 'Describe your experience working with a team versus working solo.'),
  (15, 'What tools or workflows do you rely on day to day?'),
  -- Behaviour (shared)
  (16, 'Tell me about a time you disagreed with a teammate or manager. How did you handle it?'),
  (17, 'Describe a situation where you had to meet a tight deadline. What did you do?'),
  (18, 'Give an example of when you took ownership of a problem that wasn''t strictly your responsibility.'),
  (19, 'Tell me about a mistake you made at work and how you handled it afterward.'),
  (20, 'Describe a time you had to give or receive difficult feedback.'),
  (21, 'Tell me about a time you had to adapt quickly to a change in project scope.'),
  (22, 'Describe a situation where you had incomplete information but still had to make a decision.'),
  (23, 'Tell me about a time you went beyond what was asked of you.'),
  (24, 'How do you handle competing priorities when everything feels urgent?'),
  (25, 'Describe a time you had to push back on a request you thought was wrong.'),
  -- Leadership (shared)
  (26, 'Tell me about a time you led a project or a team, formally or informally.'),
  (27, 'How do you approach mentoring a junior colleague?'),
  (28, 'Describe a time you had to motivate a team through a difficult period.'),
  (29, 'How do you handle a team member who isn''t pulling their weight?'),
  (30, 'Tell me about a decision you made that others disagreed with. How did you handle it?'),
  (31, 'How do you balance individual contribution with helping others succeed?'),
  (32, 'Describe how you''ve influenced a technical decision without having formal authority.'),
  -- Communication (shared)
  (33, 'How do you explain a technical problem to a non-technical stakeholder?'),
  (34, 'Tell me about a time miscommunication caused a problem on a project. What did you learn?'),
  (35, 'How do you keep stakeholders updated on progress during a long-running project?'),
  (36, 'Describe how you handle disagreements in writing versus in person.'),
  (37, 'How do you make sure requirements are clear before you start building?'),
  -- Culture (shared)
  (38, 'What does "doing your best work" look like to you day to day?'),
  (39, 'How do you stay current with new tools and practices in the industry?'),
  (40, 'What kind of team environment brings out your best work?'),
  (41, 'Tell me about a time your integrity was tested at work.'),
  (42, 'X Spark works under strict compliance controls for regulated clients — how do you feel about that kind of rigor?'),
  (43, 'What does work-life balance look like for you when deadlines are tight?'),
  (44, 'How do you approach work you find repetitive or unglamorous but necessary?'),
  (45, 'What would your past colleagues say is your biggest strength, and where would they say you still need to grow?'),
  -- Closing (shared)
  (46, 'Is there anything about the role or the interview process you''d like clarified?'),
  (47, 'What questions do you have for us about how the team works?'),
  (48, 'Looking back on this interview, is there anything you''d like to add or expand on?'),
  (49, 'What would make you excited to accept an offer if we extended one?'),
  (50, 'On a scale of your own expectations, how do you think this conversation went?'),
  -- Software Developer
  (51, 'Explain the difference between an interface and an abstract class in Java, and when you''d use each.'),
  (52, 'How does Python''s garbage collection work, at a high level?'),
  (53, 'Walk me through how you''d structure a PHP application to talk to a MySQL database safely.'),
  (54, 'What''s the difference between INNER JOIN and LEFT JOIN, and when would each return unexpected results?'),
  (55, 'How would you index a MySQL table that''s slow on a frequently filtered column?'),
  (56, 'Explain the difference between == and .equals() in Java.'),
  (57, 'What are Python list comprehensions and when do they hurt readability?'),
  (58, 'How does the Java Collections framework handle concurrent modification, and how do you avoid ConcurrentModificationException?'),
  (59, 'Explain connection pooling in the context of a PHP/MySQL web app under load.'),
  (60, 'How would you profile a slow Python script and decide what to optimise first?'),
  (61, 'How would you design a student enrollment system''s database schema from scratch?'),
  (62, 'What layers would you introduce between a PHP controller and MySQL, and why?'),
  (63, 'A MySQL query that used to be fast is now timing out in production. How do you investigate?'),
  (64, 'You get an intermittent NullPointerException in Java that you can''t reproduce locally. What''s your process?'),
  (65, 'How do you approach writing unit tests for a Django or Spring-style service layer?'),
  (66, 'A client reports data loss on their booking system after a deploy. Walk me through your first 30 minutes.'),
  -- Front-End Developer
  (67, 'How do you decide between useState, useReducer, and lifting state up in React?'),
  (68, 'Explain the CSS box model and a time it caused you a layout bug.'),
  (69, 'What''s the difference between var, let, and const, and why does it matter for closures?'),
  (70, 'How would you implement a responsive layout without a CSS framework?'),
  (71, 'Walk me through how the React reconciliation/virtual DOM process works at a high level.'),
  (72, 'How do you translate a Figma design into a component structure?'),
  (73, 'What accessibility issues do you check for by default in a new UI?'),
  (74, 'How would you diagnose and fix unnecessary re-renders in a React component tree?'),
  (75, 'Explain code-splitting and lazy loading in a React app, and when they''re worth the complexity.'),
  (76, 'How would you structure a design system so components stay consistent across a growing app?'),
  (77, 'How do you decide what state belongs in a global store versus local component state?'),
  (78, 'A page renders fine on desktop but breaks on mobile Safari only. How do you debug it?'),
  (79, 'Users report a form that silently fails to submit on slow connections. What do you check?'),
  (80, 'How do you approach testing components that depend on async data fetching?'),
  (81, 'A stakeholder wants a pixel-perfect Figma match but it breaks accessibility. How do you handle that conversation?'),
  -- Data & AI Engineer
  (82, 'How would you write a query to find the top 5 customers by revenue per month?'),
  (83, 'What''s the difference between a fact table and a dimension table?'),
  (84, 'How do you decide between a bar chart, a line chart, and a table in a Power BI dashboard?'),
  (85, 'Explain window functions in SQL and give an example use case.'),
  (86, 'How would you clean a dataset with inconsistent date formats and missing values?'),
  (87, 'What''s the difference between correlation and causation, and why does it matter when presenting insights?'),
  (88, 'How would you optimise a slow aggregation query over millions of rows?'),
  (89, 'How do you design a Power BI data model to avoid circular relationships?'),
  (90, 'How would you design a simple ETL pipeline from a transactional MySQL database into a reporting layer?'),
  (91, 'How would you design a dashboard that needs to refresh near-real-time without overloading the source database?'),
  (92, 'A Power BI dashboard shows numbers that don''t match the source system. How do you track down why?'),
  (93, 'How do you validate that a data pipeline is producing correct output after a schema change?'),
  (94, 'Leadership wants a dashboard by Friday but the underlying data has quality issues. What do you do?'),
  -- Cybersecurity Analyst
  (95, 'What is SQL injection and how would you prevent it in a Java or JavaScript app talking to MySQL?'),
  (96, 'Explain the difference between authentication and authorisation.'),
  (97, 'What is Cross-Site Scripting (XSS) and what are the main mitigations?'),
  (98, 'How would you securely store user passwords in a MySQL-backed application?'),
  (99, 'Walk me through the OWASP Top 10 categories you consider most relevant to a retail web application.'),
  (100, 'How would you assess the security posture of a hospitality booking system handling guest data?'),
  (101, 'What logging and monitoring would you put in place to detect a brute-force login attempt?'),
  (102, 'How would you design a incident response process for a suspected data breach in an education-sector system?'),
  (103, 'Explain the principle of least privilege and how you''d apply it to a MySQL database with multiple application roles.'),
  (104, 'A JavaScript-heavy retail site is flagged for a vulnerable third-party dependency. How do you triage it?'),
  (105, 'How would you approach a basic security review of a new feature before it ships?'),
  (106, 'You discover an unpatched vulnerability in a live client system serving education-sector users. What do you do first?'),
  -- Backend Developer
  (107, 'How does Spring''s dependency injection work, and why does it matter for testability?'),
  (108, 'Explain the difference between @Component, @Service, and @Repository in Spring Boot.'),
  (109, 'How would you design REST endpoints for a payments resource, including error handling?'),
  (110, 'What''s the difference between optimistic and pessimistic locking, and when would you use each?'),
  (111, 'Explain ACID properties and why they matter for a payments platform.'),
  (112, 'How would you design idempotency into a payment API so retries don''t double-charge a customer?'),
  (113, 'Explain how Spring manages transactions across multiple repository calls, and where it can go wrong.'),
  (114, 'How would you design a Java/Spring Boot backend to support a growing set of client integrations?'),
  (115, 'Walk me through how you''d version a public API without breaking existing consumers.'),
  (116, 'Design a high-level system for processing and reconciling daily payment transactions.'),
  (117, 'How would you secure a Spring Boot API that handles financial transactions?'),
  (118, 'A production API endpoint is intermittently returning 500s under load. How do you approach root-causing it?'),
  (119, 'How do you approach integration testing for a service that talks to a database and an external payments provider?'),
  (120, 'You''re leading a hackathon team with three days left and the payments integration is broken. What do you do?');
